version: '3'

services:
  server:
    build:
      context: https://github.com/LDAP/docker-artemis-server.git
      args:    
        ARTEMIS_VERSION: ${ARTEMIS_VERSION}
    depends_on:
      - db
      - gitlab
      - jenkins
    networks:
      - artemis
    ports:
      - 8080:8080
    environment:
      - WAIT_FOR="db:3306,gitlab:80"
    volumes:
      - ${ARTEMIS_CONFIG_DIR}:/opt/Artemis/config
      - ${ARTEMIS_DATA_DIR}:/opt/Artemis/data

  client:
    build:
      context: https://github.com/LDAP/docker-artemis-client.git
      args:    
        ARTEMIS_VERSION: ${ARTEMIS_VERSION}
    depends_on:
      - server
    networks:
      - artemis
    ports:
      - 80:80
    environment:
      - SERVER_NAME=localhost
      - API_REDIRECT_URL=http://server:8080
    volumes:
      - ${CUSTOM_LOGO}:/usr/share/nginx/html/public/images/logo.png
      - ${CUSTOM_FAVICON}:/usr/share/nginx/html/public/images/favicon.ico
      - ${CUSTOM_PRIVACY_STATEMENT}:/usr/share/nginx/html/public/content/privacy_statement.html

  db:
    image: mysql:8.0.23
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=Artemis
    networks:
      - artemis
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab
    ports:
      - 8880:80
      - 8443:443
      - "2222:22"
    volumes:
      - ${GITLAB_DATA_DIR}:/var/opt/gitlab
      - ${GITLAB_LOG_DIR}:/var/log/gitlab
      - ${GITLAB_CONFIG_DIR}:/etc/gitlab
    networks:
      - artemis

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 7780:8080
      - 50000:50000
    volumes:
      - ${JENKINS_DATA_DIR}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/bin/com.docker.cli:/usr/bin/com.docker.cli:ro
    networks:
      - artemis

networks:
  artemis:
    driver: bridge
